name: Pulse
description: "Pulse Office Version"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  # State Management & DI
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # UI & Aesthetics
  google_fonts: any
  flutter_svg: ^2.0.17

  # Functional Features
  geolocator: any
  dio: any
  path_provider: any
  path: any

  # Security & Local Storage
  flutter_secure_storage: 9.2.2

  # Utilities
  intl: ^0.19.0
  json_annotation: any
  permission_handler: any
  device_info_plus: any
  flutter_localizations:
    sdk: flutter
  uuid: ^4.5.3
  android_id: 0.3.6
  worldtime: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  riverpod_generator: any
  json_serializable: any
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
